### ISSUE TITLE
feat(api): add new endpoint with aggregation for tags

### ISSUE THREAD

**Issue by dewita** [SourceCodeOER/sourcecode_api#80]
**What**

An endpoint that is able to give categories with tags which contain the number of exercises related to the tag. This endpoint is not supposed to be dynamic in terms of the actual search request of exercises, just a static one.

**Spec**

- POST or GET request ?
- In the payload/query parameters :
  - _states_ property that is an array of states an exercise can take. If empty, give a response in terms of all states. 
- Sort every tags in a category in a _DESC_ way

**Comment by jy95** [comment]
It is so paintful that I will use an [MATERIALIZED VIEW](https://www.postgresqltutorial.com/postgresql-materialized-views/), let me explain it in detail ...

# Why ?
- Unlike `Exercise_Metrics` , there is too many cases to handle (that hooks in Sequelize don't solve ) : 
  * When a tag is inserted into the system
  * When an exercise is inserted into the system with his tags ( as partial soumission is not allowed)
  * When an exercise changed his tags, 3 scenarios are possible : 
      * simple addition : gives +1 to each of his tag in the right column ( depending of his state)
      * simple removal : gives -1 to each of his tag in the right column ( depending of his state)
      * the most complex case : A nightmare ...
  * When an exercise / multiple exercises changed their state ...
  * When an exercise / multiple exercises got deleted ...
  * When a tag / multiple tags got deleted
  * When a tag category / multiple tag categories got deleted
  * .... ( I could continue but I think you see my point, no ? )

# **What will be added ?**

1. the view itself I need : 

```sql
SELECT
	et."tag_id" AS "tag_id",
	COUNT(DISTINCT ex.id) FILTER (WHERE ex.state = 'DRAFT') AS "total_draft",
	COUNT(DISTINCT ex.id) FILTER (WHERE ex.state = 'PENDING') AS "total_pending",
	COUNT(DISTINCT ex.id) FILTER (WHERE ex.state = 'VALIDATED') AS "total_validated",
	COUNT(DISTINCT ex.id) FILTER (WHERE ex.state = 'NOT_VALIDATED') AS "total_not_validated",
	COUNT(DISTINCT ex.id) FILTER (WHERE ex.state = 'ARCHIVED') AS "total_archived"
FROM "exercises_library"."Exercises" ex
LEFT JOIN "exercises_library"."Exercises_Tags" et
ON et."exercise_id" = ex.id
GROUP BY et."tag_id"
```

2. An unique index 

```sql
CREATE UNIQUE INDEX rental_category ON myView(tag_id);
```

so I can do in my trigger ( so that we ) : 

```sql
REFRESH MATERIALIZED VIEW CONCURRENTLY myView
```

Explanation : 

>When you refresh data for a materialized view, PosgreSQL locks the entire table therefore you cannot query data against it. To avoid this, you can use the CONCURRENTLY option.
With CONCURRENTLY option, PostgreSQL creates a temporary updated version of the materialized view, compares two versions, and performs INSERT and UPDATE only the differences. You can query against the materialized view while it is being updated. One requirement for using CONCURRENTLY option is that the materialized view must have a UNIQUE index. Notice that CONCURRENTLY option is only available from PosgreSQL 9.4.

3. An migration file to insert the view and triggers + force 

TBA 

As I mainly used transactions for many scenarios, [triggers](https://www.postgresql.org/docs/current/sql-createtrigger.html) on tables "Exercises_Tags" and "Exercises" should be enough.
